on:
  issue_comment:
    types: [created, edited]
name: Issue Comment
jobs:
  issueCommentHandler:
    name: IssueCommentHandler
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: IssueCommentHandler
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
